---
- name: Connect to Tomcat server 
  uri:
    url: http://localhost:9090
  register: result
  until: "result.status == 200"
  retries: 5
  delay: 10

- name: status debian
  debug:
    var: result


...
