---
- name: Copy username and password from tomcat-users.xml file
  copy:
   src: "{{file1}}"
   dest: "{{destination1}}"
- name: Change port number from 8080 to 9090
  replace:
   path: "{{path1}}"
   regexp: "{{port1}}"
   replace: "{{port2}}"
  notify: check url response
...
