---
- name: Connect to Tomcat server 
  uri:
    url: http://20.235.66.56:8080
  register: result
  until: "result.status == 200"
  retries: 5
  delay: 10
- name: status
  debug:
     var: result


...
